import "./globals.css";
import { Toaster } from "react-hot-toast";
import MuiThemeProvider from "@/components/providers/MuiThemeProvider";

export const metadata = {
  title: "E-Learning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MuiThemeProvider>
          {children}
          <Toaster position="top-center" />
        </MuiThemeProvider>
      </body>
    </html>
  );
}
